spring:
    datasource:
        url: jdbc:h2:tcp://localhost/mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        driver-class-name: org.h2.Driver
        connection-timeout: 5000
        idle-timeout: 12000
        max-lifetime: 900000
        minimum-idle: 5
        maximum-pool-size: 80
        connection-test-query: SELECT 1
    jpa:
      database: h2
      show-sql: true
      hibernate:
        ddl-auto: create
        naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          batch_size: 0
      properties:
        dialect: org.hibernate.dialect.H2Dialect